ALTER TABLE `teams` ADD COLUMN `slug` text NOT NULL DEFAULT 'pending-slug';
--> statement-breakpoint
UPDATE `teams`
SET `slug` =
  CASE (`id` % 35)
    WHEN 0 THEN 'amber'
    WHEN 1 THEN 'anchor'
    WHEN 2 THEN 'atlas'
    WHEN 3 THEN 'beacon'
    WHEN 4 THEN 'brisk'
    WHEN 5 THEN 'cedar'
    WHEN 6 THEN 'cinder'
    WHEN 7 THEN 'clover'
    WHEN 8 THEN 'cobalt'
    WHEN 9 THEN 'comet'
    WHEN 10 THEN 'copper'
    WHEN 11 THEN 'delta'
    WHEN 12 THEN 'ember'
    WHEN 13 THEN 'fable'
    WHEN 14 THEN 'frost'
    WHEN 15 THEN 'harbour'
    WHEN 16 THEN 'indigo'
    WHEN 17 THEN 'juno'
    WHEN 18 THEN 'keystone'
    WHEN 19 THEN 'lagoon'
    WHEN 20 THEN 'lantern'
    WHEN 21 THEN 'maple'
    WHEN 22 THEN 'meadow'
    WHEN 23 THEN 'meridian'
    WHEN 24 THEN 'nova'
    WHEN 25 THEN 'onyx'
    WHEN 26 THEN 'orbit'
    WHEN 27 THEN 'pebble'
    WHEN 28 THEN 'quartz'
    WHEN 29 THEN 'ripple'
    WHEN 30 THEN 'summit'
    WHEN 31 THEN 'tempo'
    WHEN 32 THEN 'velvet'
    WHEN 33 THEN 'willow'
    ELSE 'zenith'
  END
  || '-' ||
  CASE ((`id` / 35) % 35)
    WHEN 0 THEN 'amber'
    WHEN 1 THEN 'anchor'
    WHEN 2 THEN 'atlas'
    WHEN 3 THEN 'beacon'
    WHEN 4 THEN 'brisk'
    WHEN 5 THEN 'cedar'
    WHEN 6 THEN 'cinder'
    WHEN 7 THEN 'clover'
    WHEN 8 THEN 'cobalt'
    WHEN 9 THEN 'comet'
    WHEN 10 THEN 'copper'
    WHEN 11 THEN 'delta'
    WHEN 12 THEN 'ember'
    WHEN 13 THEN 'fable'
    WHEN 14 THEN 'frost'
    WHEN 15 THEN 'harbour'
    WHEN 16 THEN 'indigo'
    WHEN 17 THEN 'juno'
    WHEN 18 THEN 'keystone'
    WHEN 19 THEN 'lagoon'
    WHEN 20 THEN 'lantern'
    WHEN 21 THEN 'maple'
    WHEN 22 THEN 'meadow'
    WHEN 23 THEN 'meridian'
    WHEN 24 THEN 'nova'
    WHEN 25 THEN 'onyx'
    WHEN 26 THEN 'orbit'
    WHEN 27 THEN 'pebble'
    WHEN 28 THEN 'quartz'
    WHEN 29 THEN 'ripple'
    WHEN 30 THEN 'summit'
    WHEN 31 THEN 'tempo'
    WHEN 32 THEN 'velvet'
    WHEN 33 THEN 'willow'
    ELSE 'zenith'
  END
  || '-' ||
  CASE ((`id` / 1225) % 35)
    WHEN 0 THEN 'amber'
    WHEN 1 THEN 'anchor'
    WHEN 2 THEN 'atlas'
    WHEN 3 THEN 'beacon'
    WHEN 4 THEN 'brisk'
    WHEN 5 THEN 'cedar'
    WHEN 6 THEN 'cinder'
    WHEN 7 THEN 'clover'
    WHEN 8 THEN 'cobalt'
    WHEN 9 THEN 'comet'
    WHEN 10 THEN 'copper'
    WHEN 11 THEN 'delta'
    WHEN 12 THEN 'ember'
    WHEN 13 THEN 'fable'
    WHEN 14 THEN 'frost'
    WHEN 15 THEN 'harbour'
    WHEN 16 THEN 'indigo'
    WHEN 17 THEN 'juno'
    WHEN 18 THEN 'keystone'
    WHEN 19 THEN 'lagoon'
    WHEN 20 THEN 'lantern'
    WHEN 21 THEN 'maple'
    WHEN 22 THEN 'meadow'
    WHEN 23 THEN 'meridian'
    WHEN 24 THEN 'nova'
    WHEN 25 THEN 'onyx'
    WHEN 26 THEN 'orbit'
    WHEN 27 THEN 'pebble'
    WHEN 28 THEN 'quartz'
    WHEN 29 THEN 'ripple'
    WHEN 30 THEN 'summit'
    WHEN 31 THEN 'tempo'
    WHEN 32 THEN 'velvet'
    WHEN 33 THEN 'willow'
    ELSE 'zenith'
  END;
--> statement-breakpoint
CREATE UNIQUE INDEX `teams_slug_unique` ON `teams` (`slug`);
