name = "sprintjam"
main = "src/index.js"
compatibility_date = "2023-01-01"

[durable_objects]
bindings = [
  { name = "POKER_ROOM", class_name = "PokerRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["PokerRoom"]