import {
  type RouteConfig,
  index,
  prefix,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("changelog", "routes/changelog.tsx"),
  route("faq", "routes/faq.tsx"),
  route("integrations", "routes/integrations.tsx"),
  ...prefix("integrations", [
    route("jira", "routes/integrations/jira.tsx"),
    route("linear", "routes/integrations/linear.tsx"),
    route("github", "routes/integrations/github.tsx"),
  ]),
  route("guides", "routes/guides.tsx"),
  ...prefix("guides", [
    route("planning-poker", "routes/guides/planning-poker.tsx"),
    route("fibonacci-scale", "routes/guides/fibonacci-scale.tsx"),
    route("fibonacci-short", "routes/guides/fibonacci-short.tsx"),
    route("doubling-scale", "routes/guides/doubling-scale.tsx"),
    route("tshirt-sizing", "routes/guides/tshirt-sizing.tsx"),
    route("planet-scale", "routes/guides/planet-scale.tsx"),
    route("yes-no", "routes/guides/yes-no.tsx"),
    route("simple-scale", "routes/guides/simple-scale.tsx"),
    route("hours-estimates", "routes/guides/hours-estimates.tsx"),
    route("session-roles", "routes/guides/session-roles.tsx"),
    route("remote-estimation", "routes/guides/remote-estimation.tsx"),
    route("story-points", "routes/guides/story-points.tsx"),
    route("sprint-planning", "routes/guides/sprint-planning.tsx"),
    route("consensus-building", "routes/guides/consensus-building.tsx"),
    route("structured-voting", "routes/guides/structured-voting.tsx"),
  ]),
  ...prefix("auth", [route("login", "routes/auth/login.tsx")]),
  route("create", "routes/create.tsx"),
  route("join", "routes/join.tsx"),
  route("room/:roomKey", "routes/room/$roomKey.tsx"),
  route("wheel", "routes/wheel/index.tsx"),
  route("wheel/:wheelKey", "routes/wheel/$wheelKey.tsx"),
  route("standup", "routes/standup/index.tsx"),
  ...prefix("standup", [
    route("create", "routes/standup/create.tsx"),
    route("join", "routes/standup/join.tsx"),
    route("join/:standupKey", "routes/standup/join.$standupKey.tsx"),
    route("room/:standupKey", "routes/standup/room.$standupKey.tsx"),
  ]),
  route("workspace", "routes/workspace/index.tsx"),
  ...prefix("workspace", [
    route("profile", "routes/workspace/profile.tsx"),
    route("sessions", "routes/workspace/sessions.tsx"),
    route("admin", "routes/workspace/admin.tsx"),
    route("admin/teams", "routes/workspace/admin/teams.tsx"),
    route("admin/teams/settings", "routes/workspace/admin/teams/settings.tsx"),
  ]),
  route("404", "routes/404.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
