/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1b947ecbb64022316e26720a86dca31d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env {
    ENVIRONMENT: "production" | "development" | "staging";
    ENABLE_MAGIC_LINK_RATE_LIMIT: "true" | "false";
    RESEND_API_KEY: string;
    DB: D1Database;
    MAGIC_LINK_RATE_LIMITER: RateLimit;
  }
}
interface Env extends Cloudflare.Env {}
