/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ade178ab47ebf4ffb30dcceb444b2bfc)
interface __BaseEnv_Env {
  DB: D1Database;
  SEND_EMAIL: SendEmail;
  ENVIRONMENT: "development" | "production";
  ENABLE_MAGIC_LINK_RATE_LIMIT: "false" | "true";
  MAGIC_LINK_RATE_LIMITER?: RateLimit;
  VERIFICATION_RATE_LIMITER?: RateLimit;
  IP_RATE_LIMITER?: RateLimit;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface DevelopmentEnv {
    DB: D1Database;
    SEND_EMAIL: SendEmail;
    ENVIRONMENT: "development";
    ENABLE_MAGIC_LINK_RATE_LIMIT: "false";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ENVIRONMENT" | "ENABLE_MAGIC_LINK_RATE_LIMIT">
  > {}
}
