/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a4aaf6df045deccc1fd55415888e3629)
export {};
declare global {
	const ENVIRONMENT: "production" | "development" | "staging";
	const RESEND_API_KEY: string;
	const DB: D1Database;
}
