export const ONE_WORD_PITCH_PROMPTS = [
  "New app for dogs",
  "Worst sprint retro ever",
  "Monday deployment surprise",
  "Unexpected stand-up confession",
  "Ticket title from chaos mode",
  "AI pair programmer after coffee",
  "Refactor that touched everything",
  "Bug fix that made three more bugs",
  "Backlog item everyone avoided",
  "Release note nobody wanted to write",
];

export const CATEGORY_BLITZ_CATEGORIES = [
  "Dev tools",
  "Agile ceremonies",
  "Sprint smells",
  "Ticket statuses",
  "Code review phrases",
  "Team rituals",
  "Testing terms",
  "Deployment mishaps",
];

export const CATEGORY_BLITZ_LETTERS = [
  "A",
  "B",
  "C",
  "D",
  "F",
  "G",
  "L",
  "M",
  "P",
  "R",
  "S",
  "T",
];

export const CLUEBOARD_WORD_BANK = [
  "backlog",
  "burnup",
  "burndown",
  "branch",
  "bug",
  "build",
  "capacity",
  "chore",
  "commit",
  "deploy",
  "design",
  "estimate",
  "epic",
  "feature",
  "fibonacci",
  "grooming",
  "handoff",
  "hotfix",
  "incident",
  "issue",
  "kanban",
  "latency",
  "merge",
  "milestone",
  "planning",
  "points",
  "polling",
  "priority",
  "qa",
  "queue",
  "refactor",
  "release",
  "retro",
  "review",
  "scope",
  "scrum",
  "ship",
  "spike",
  "standup",
  "story",
  "sprint",
  "squad",
  "sync",
  "task",
  "techdebt",
  "testing",
  "ticket",
  "triage",
  "velocity",
  "workflow",
];
