export const ONE_WORD_PITCH_PROMPTS = [
  "New app for dogs",
  "Worst sprint retro ever",
  "Monday deployment surprise",
  "Unexpected stand-up confession",
  "Ticket title from chaos mode",
  "AI pair programmer after coffee",
  "Refactor that touched everything",
  "Bug fix that made three more bugs",
  "Backlog item everyone avoided",
  "Release note nobody wanted to write",
  "Stakeholder asks for one tiny change",
  "PRD rewritten during planning poker",
  "Designer, PM and engineer walk into backlog grooming",
  "Velocity chart right before holiday season",
  "Demo that worked only in staging",
  "Analyst finds the metric nobody wanted",
  "Roadmap slide with too many priorities",
  "Prototype approved by complete accident",
  "Stand-up update that needed its own incident review",
  "Sprint goal translated by committee",
  "User journey with four impossible steps",
  "Leadership status update five minutes before launch",
  "Accessibility bug discovered in the demo",
  "Data dashboard everyone interpreted differently",
  "Scope creep disguised as feedback",
];

export const CATEGORY_BLITZ_CATEGORIES = [
  "Dev tools",
  "Agile ceremonies",
  "Sprint smells",
  "Ticket statuses",
  "Code review phrases",
  "Team rituals",
  "Testing terms",
  "Deployment mishaps",
  "Product artefacts",
  "UX research methods",
  "UX deliverables",
  "Engineering practices",
  "Data concepts",
  "Metrics and KPIs",
  "Management phrases",
  "Stakeholder requests",
  "Planning inputs",
  "Delivery risks",
  "Collaboration tools",
  "Agile roles",
];

export const CATEGORY_BLITZ_LETTERS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "K",
  "L",
  "M",
  "O",
  "P",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
];

export const SPRINT_WORD_BANK = [
  "AGILE",
  "ALIGN",
  "AMBER",
  "BRAIN",
  "BRIEF",
  "SPIKE",
  "STORY",
  "SCOPE",
  "MERGE",
  "QUEUE",
  "RETRO",
  "SCRUM",
  "SQUAD",
  "STACK",
  "STAND",
  "GROOM",
  "BUILD",
  "CHECK",
  "CHURN",
  "CLEAN",
  "CLICK",
  "COACH",
  "COUNT",
  "STAGE",
  "CHART",
  "CROSS",
  "DAILY",
  "DEBUG",
  "DELAY",
  "DEMOS",
  "DRAFT",
  "DRIFT",
  "EPICS",
  "FETCH",
  "FIXES",
  "FOCUS",
  "FORMS",
  "GOALS",
  "GRAPH",
  "GROUP",
  "GUARD",
  "IDEAS",
  "INDEX",
  "ISSUE",
  "LABEL",
  "LAYER",
  "LEADS",
  "LIMIT",
  "MODEL",
  "OWNER",
  "PANEL",
  "PILOT",
  "PIXEL",
  "PLANS",
  "POKER",
  "PRIOR",
  "TRACK",
  "BENCH",
  "AUDIT",
  "QUERY",
  "PARSE",
  "PATCH",
  "CACHE",
  "RECAP",
  "RISKS",
  "ROLES",
  "ROUTE",
  "SCORE",
  "PIVOT",
  "SCALE",
  "SHAPE",
  "SKILL",
  "SMELL",
  "STAFF",
  "START",
  "STUDY",
  "TASKS",
  "TEAMS",
  "TESTS",
  "THEME",
  "TRACE",
  "TREND",
  "TRUST",
  "TWEAK",
  "VALUE",
  "VIEWS",
  "VOTES",
];

export const TEAM_THREADS_PUZZLES: Array<{
  groups: Array<{
    category: string;
    words: string[];
    difficulty: 1 | 2 | 3 | 4;
  }>;
}> = [
  {
    groups: [
      {
        category: "Scrum ceremonies",
        words: ["STANDUP", "RETRO", "PLANNING", "REVIEW"],
        difficulty: 1,
      },
      {
        category: "Testing types",
        words: ["UNIT", "SMOKE", "LOAD", "E2E"],
        difficulty: 2,
      },
      {
        category: "___ request",
        words: ["PULL", "MERGE", "ACCESS", "CHANGE"],
        difficulty: 3,
      },
      {
        category: "Fibonacci numbers",
        words: ["ONE", "TWO", "THREE", "FIVE"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Sprint artifacts",
        words: ["BACKLOG", "BURNDOWN", "VELOCITY", "ROADMAP"],
        difficulty: 1,
      },
      {
        category: "Git commands",
        words: ["COMMIT", "PUSH", "FETCH", "REBASE"],
        difficulty: 2,
      },
      {
        category: "Ways to ship",
        words: ["DEPLOY", "RELEASE", "LAUNCH", "ROLLOUT"],
        difficulty: 3,
      },
      {
        category: "___ driven",
        words: ["TEST", "DATA", "DOMAIN", "EVENT"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Team rituals",
        words: ["STANDUP", "KICKOFF", "DEMO", "SYNC"],
        difficulty: 1,
      },
      {
        category: "Ticket statuses",
        words: ["OPEN", "BLOCKED", "REVIEW", "CLOSED"],
        difficulty: 2,
      },
      {
        category: "Deployment mishaps",
        words: ["ROLLBACK", "HOTFIX", "INCIDENT", "OUTAGE"],
        difficulty: 3,
      },
      {
        category: "Always 'almost done'",
        words: ["DESIGN", "TESTING", "DOCS", "MIGRATION"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Agile roles",
        words: ["MASTER", "OWNER", "DEVELOPER", "TESTER"],
        difficulty: 1,
      },
      {
        category: "Code review phrases",
        words: ["LGTM", "NITS", "BLOCKING", "APPROVED"],
        difficulty: 2,
      },
      {
        category: "Things in a repo",
        words: ["BRANCH", "TAG", "COMMIT", "HOOK"],
        difficulty: 3,
      },
      {
        category: "Sprint planning poker values",
        words: ["ONE", "THREE", "EIGHT", "INFINITY"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Product artefacts",
        words: ["PRD", "ROADMAP", "BACKLOG", "BRIEF"],
        difficulty: 1,
      },
      {
        category: "UX research methods",
        words: ["SURVEY", "INTERVIEW", "OBSERVE", "SORT"],
        difficulty: 2,
      },
      {
        category: "Data artefacts",
        words: ["CHART", "FUNNEL", "COHORT", "DASHBOARD"],
        difficulty: 3,
      },
      {
        category: "___ map",
        words: ["HEAT", "SITE", "STORY", "JOURNEY"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Engineering specialisms",
        words: ["FRONTEND", "BACKEND", "DEVOPS", "PLATFORM"],
        difficulty: 1,
      },
      {
        category: "Prioritisation frameworks",
        words: ["RICE", "WSJF", "KANO", "MOSCOW"],
        difficulty: 2,
      },
      {
        category: "Leadership concerns",
        words: ["BUDGET", "HEADCOUNT", "TIMELINE", "RISK"],
        difficulty: 3,
      },
      {
        category: "___ debt",
        words: ["TECH", "DESIGN", "DATA", "PROCESS"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "UX deliverables",
        words: ["WIREFRAME", "PROTOTYPE", "MOCKUP", "SITEMAP"],
        difficulty: 1,
      },
      {
        category: "Product metrics",
        words: ["CHURN", "ADOPTION", "RETENTION", "ENGAGEMENT"],
        difficulty: 2,
      },
      {
        category: "Collaboration tools",
        words: ["JIRA", "FIGMA", "SLACK", "MIRO"],
        difficulty: 3,
      },
      {
        category: "___ test",
        words: ["USER", "SMOKE", "LOAD", "AB"],
        difficulty: 4,
      },
    ],
  },
  {
    groups: [
      {
        category: "Planning inputs",
        words: ["CAPACITY", "PRIORITY", "DEPENDENCY", "HOLIDAYS"],
        difficulty: 1,
      },
      {
        category: "Leadership titles",
        words: ["MANAGER", "DIRECTOR", "LEAD", "VP"],
        difficulty: 2,
      },
      {
        category: "Analyst verbs",
        words: ["QUERY", "SEGMENT", "FORECAST", "MODEL"],
        difficulty: 3,
      },
      {
        category: "___ sync",
        words: ["TEAM", "DESIGN", "DATA", "LEADERSHIP"],
        difficulty: 4,
      },
    ],
  },
];

export const CLUEBOARD_WORD_BANK = [
  "a11y",
  "acceptance",
  "adoption",
  "agile",
  "alignment",
  "analyst",
  "analytics",
  "architecture",
  "assumption",
  "backlog",
  "baseline",
  "benchmark",
  "board",
  "burnup",
  "burndown",
  "branch",
  "bug",
  "build",
  "capacity",
  "cohort",
  "collaboration",
  "comment",
  "chore",
  "commit",
  "copy",
  "customer",
  "dashboard",
  "data",
  "decision",
  "deploy",
  "dependency",
  "designer",
  "design",
  "diagram",
  "discovery",
  "documentation",
  "engineering",
  "estimate",
  "epic",
  "experiment",
  "feature",
  "figma",
  "fibonacci",
  "flow",
  "forecast",
  "friction",
  "grooming",
  "handoff",
  "hotfix",
  "hypothesis",
  "incident",
  "insight",
  "issue",
  "iteration",
  "jira",
  "kanban",
  "kpi",
  "latency",
  "leadership",
  "manager",
  "merge",
  "metric",
  "milestone",
  "miro",
  "mockup",
  "notion",
  "okr",
  "outcome",
  "ownership",
  "persona",
  "pipeline",
  "planning",
  "points",
  "polling",
  "postmortem",
  "prd",
  "priority",
  "prototype",
  "qa",
  "query",
  "queue",
  "refinement",
  "refactor",
  "release",
  "research",
  "retention",
  "retro",
  "review",
  "roadmap",
  "rollout",
  "scopecreep",
  "segment",
  "shipit",
  "slack",
  "scope",
  "scrum",
  "sprintgoal",
  "stakeholder",
  "ship",
  "spike",
  "standup",
  "storymap",
  "story",
  "sprint",
  "squad",
  "sync",
  "task",
  "telemetry",
  "techdebt",
  "testing",
  "ticket",
  "triage",
  "usability",
  "userflow",
  "velocity",
  "warehouse",
  "wireframe",
  "workflow",
  "workshop",
  "wsjf",
];
