import { Fetcher } from '@cloudflare/workers-types';

/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ac751c8b091bf83785bce68edfd1e77)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./api/index');
  }
  interface Env {
    ROOM_WORKER: Fetcher /* sprintjam-room-worker */;
    AUTH_WORKER: Fetcher /* sprintjam-auth-worker */;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
