/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6183a93b82460a48679aceacbf07365c)
interface __BaseEnv_Env {
  ENVIRONMENT: "development" | "production";
  ROOM_WORKER:
    | Fetcher /* sprintjam-room-worker-development */
    | Fetcher /* sprintjam-room-worker */;
  AUTH_WORKER:
    | Fetcher /* sprintjam-auth-worker-development */
    | Fetcher /* sprintjam-auth-worker */;
  STATS_WORKER:
    | Fetcher /* sprintjam-stats-worker-development */
    | Fetcher /* sprintjam-stats-worker */;
  WHEEL_WORKER:
    | Fetcher /* sprintjam-wheel-worker-development */
    | Fetcher /* sprintjam-wheel-worker */;
  STANDUP_WORKER:
    | Fetcher /* sprintjam-standup-worker-development */
    | Fetcher /* sprintjam-standup-worker */;
  RETRO_WORKER:
    | Fetcher /* sprintjam-retro-worker-development */
    | Fetcher /* sprintjam-retro-worker */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./api/index");
  }
  interface DevelopmentEnv {
    ENVIRONMENT: "development";
    ROOM_WORKER: Fetcher /* sprintjam-room-worker-development */;
    AUTH_WORKER: Fetcher /* sprintjam-auth-worker-development */;
    STATS_WORKER: Fetcher /* sprintjam-stats-worker-development */;
    WHEEL_WORKER: Fetcher /* sprintjam-wheel-worker-development */;
    STANDUP_WORKER: Fetcher /* sprintjam-standup-worker-development */;
    RETRO_WORKER: Fetcher /* sprintjam-retro-worker-development */;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ENVIRONMENT">
  > {}
}
