/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2abc199b9c06356c0197c216b6c2fb93)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./api/index");
  }
  interface Env {
    ENVIRONMENT: "production" | "development" | "staging";
    POLYCHAT_API_TOKEN: string;
    JIRA_OAUTH_CLIENT_ID: string;
    JIRA_OAUTH_CLIENT_SECRET: string;
    JIRA_OAUTH_REDIRECT_URI: string;
    LINEAR_OAUTH_CLIENT_ID: string;
    LINEAR_OAUTH_CLIENT_SECRET: string;
    LINEAR_OAUTH_REDIRECT_URI: string;
    GITHUB_OAUTH_CLIENT_ID: string;
    GITHUB_OAUTH_CLIENT_SECRET: string;
    GITHUB_OAUTH_REDIRECT_URI: string;
    TOKEN_ENCRYPTION_SECRET: string;
    FEEDBACK_GITHUB_TOKEN: string;
    RESEND_API_KEY: string;
    ROOM_WORKER: Fetcher /* sprintjam-room-worker */;
    AUTH_WORKER: Fetcher /* sprintjam-auth-worker */;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
