/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 25177b5e7b20860206011c9e6a83ee39)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "PlanningRoom";
  }
  interface Env {
    ENVIRONMENT: "development" | "staging";
    POLYCHAT_API_TOKEN: string;
    JIRA_OAUTH_CLIENT_ID: string;
    JIRA_OAUTH_CLIENT_SECRET: string;
    JIRA_OAUTH_REDIRECT_URI: string;
    LINEAR_OAUTH_CLIENT_ID: string;
    LINEAR_OAUTH_CLIENT_SECRET: string;
    LINEAR_OAUTH_REDIRECT_URI: string;
    GITHUB_OAUTH_CLIENT_ID: string;
    GITHUB_OAUTH_CLIENT_SECRET: string;
    GITHUB_OAUTH_REDIRECT_URI: string;
    TOKEN_ENCRYPTION_SECRET: string;
    FEEDBACK_GITHUB_TOKEN: string;
    PLANNING_ROOM: DurableObjectNamespace<import("./src/index").PlanningRoom>;
    JOIN_RATE_LIMITER: RateLimit;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ENVIRONMENT"
      | "POLYCHAT_API_TOKEN"
      | "JIRA_OAUTH_CLIENT_ID"
      | "JIRA_OAUTH_CLIENT_SECRET"
      | "JIRA_OAUTH_REDIRECT_URI"
      | "LINEAR_OAUTH_CLIENT_ID"
      | "LINEAR_OAUTH_CLIENT_SECRET"
      | "LINEAR_OAUTH_REDIRECT_URI"
      | "GITHUB_OAUTH_CLIENT_ID"
      | "GITHUB_OAUTH_CLIENT_SECRET"
      | "GITHUB_OAUTH_REDIRECT_URI"
      | "TOKEN_ENCRYPTION_SECRET"
      | "FEEDBACK_GITHUB_TOKEN"
    >
  > {}
}
declare module "*.sql" {
  const value: string;
  export default value;
}
