/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1e2e92845c49eecc175432e77126c912)
interface __BaseEnv_Env {
  ENVIRONMENT: "development" | "production";
  ENABLE_JOIN_RATE_LIMIT: "false" | "true";
  PLANNING_ROOM: DurableObjectNamespace<import("./src/index").PlanningRoom>;
  STATS_WORKER:
    | Fetcher /* sprintjam-stats-worker-development */
    | Fetcher /* sprintjam-stats-worker */;
  AUTH_WORKER:
    | Fetcher /* sprintjam-auth-worker-development */
    | Fetcher /* sprintjam-auth-worker */;
  JOIN_RATE_LIMITER?: RateLimit;
  FEEDBACK_RATE_LIMITER?: RateLimit;
  OAUTH_RATE_LIMITER?: RateLimit;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "PlanningRoom";
  }
  interface DevelopmentEnv {
    ENVIRONMENT: "development";
    ENABLE_JOIN_RATE_LIMIT: "false";
    PLANNING_ROOM: DurableObjectNamespace<import("./src/index").PlanningRoom>;
    STATS_WORKER: Fetcher /* sprintjam-stats-worker-development */;
    AUTH_WORKER: Fetcher /* sprintjam-auth-worker-development */;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ENVIRONMENT" | "ENABLE_JOIN_RATE_LIMIT">
  > {}
}
declare module "*.sql" {
  const value: string;
  export default value;
}
