/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 00db2cfa8f6588d052f9f18218956c35)
declare namespace Cloudflare {
	interface Env {
		ENVIRONMENT: "development" | "staging";
		POLYCHAT_API_TOKEN: string;
		JIRA_OAUTH_CLIENT_ID: string;
		JIRA_OAUTH_CLIENT_SECRET: string;
		JIRA_OAUTH_REDIRECT_URI: string;
		LINEAR_OAUTH_CLIENT_ID: string;
		LINEAR_OAUTH_CLIENT_SECRET: string;
		LINEAR_OAUTH_REDIRECT_URI: string;
		GITHUB_OAUTH_CLIENT_ID: string;
		GITHUB_OAUTH_CLIENT_SECRET: string;
		GITHUB_OAUTH_REDIRECT_URI: string;
		TOKEN_ENCRYPTION_SECRET: string;
		FEEDBACK_GITHUB_TOKEN: string;
		PLANNING_ROOM: DurableObjectNamespace /* PlanningRoom */;
		JOIN_RATE_LIMITER: RateLimit;
	}
}
interface Env extends Cloudflare.Env {}
declare module "*.sql" {
	const value: string;
	export default value;
}